# Generated by Django 5.2.4 on 2025-12-23 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0003_savingproducts_savingoptions_savingsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositproducts',
            name='fin_co_no',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='savingproducts',
            name='fin_co_no',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
