# Generated by Django 5.2.4 on 2025-12-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
