# Generated by Django 5.2.4 on 2025-12-23 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_infos', '0004_alter_commentinfo_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_articles_infos', to=settings.AUTH_USER_MODEL),
        ),
    ]
