# Generated by Django 5.2.4 on 2025-12-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="article",
        ),
    ]
