# Generated by Django 5.2.4 on 2025-11-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_news_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_bookmarked",
            field=models.BooleanField(default=False),
        ),
    ]
