# Generated by Django 5.2.4 on 2025-12-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('link', models.URLField(unique=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('press', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
