# Generated by Django 5.2.4 on 2025-12-24 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_news', '0002_remove_newsarticle_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-published_date', '-crawled_at']},
        ),
    ]
