# Generated by Django 5.2.4 on 2025-12-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_userfinancialinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='group',
            field=models.CharField(choices=[('CASH', '현금성 자산'), ('INVEST', '투자 자산'), ('DEBT', '부채')], default='CASH', max_length=10),
        ),
    ]
