# Generated by Django 5.2.4 on 2025-12-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetcategory_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
