# Generated by Django 5.2.4 on 2025-11-14 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepositProducts",
            fields=[
                (
                    "fin_prdt_cd",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("kor_co_nm", models.CharField(max_length=100)),
                ("fin_prdt_nm", models.CharField(max_length=200)),
                ("etc_note", models.TextField(blank=True, null=True)),
                (
                    "join_deny",
                    models.IntegerField(
                        choices=[(1, "제한없음"), (2, "서민전용"), (3, "일부제한")],
                        default=1,
                    ),
                ),
                ("join_member", models.TextField(blank=True, null=True)),
                ("join_way", models.CharField(blank=True, max_length=100, null=True)),
                ("spcl_cnd", models.TextField(blank=True, null=True)),
                ("mtrt_int", models.TextField(blank=True, null=True)),
                ("max_limit", models.BigIntegerField(blank=True, null=True)),
                ("dcls_month", models.CharField(max_length=6)),
                (
                    "dcls_strt_day",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("dcls_end_day", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "fin_co_subm_day",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepositOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intr_rate_type", models.CharField(max_length=10)),
                ("intr_rate_type_nm", models.CharField(max_length=50)),
                ("save_trm", models.IntegerField()),
                ("intr_rate", models.FloatField(default=-1)),
                ("intr_rate2", models.FloatField(default=-1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="finances.depositproducts",
                    ),
                ),
            ],
            options={
                "unique_together": {("product", "intr_rate_type", "save_trm")},
            },
        ),
    ]
